version: 2

models:
  - name: int_production__products
    description: "Intermediate model combining products with their brand, category, and stock quantity per store."
    columns:
      - name: store_product_id
        description: "Unique identifier for product in store"
        tests:
          - not_null
      - name: product_id
        description: "Unique identifier for the product."
        tests:
          - not_null
          - relationships:
              name: product_id_fk_to_products
              arguments:
                to: ref('stg_production__products')
                field: product_id
      - name: product_name
        description: "Name of the product."
      - name: brand_name
        description: "Brand associated with the product."
      - name: category_name
        description: "Category of the product."
      - name: store_id
        description: "Identifier of the store where stock is available."
        tests:
          - relationships:
              name: store_id_fk_to_stores
              arguments:
                to: ref('stg_sales__stores')
                field: store_id
      - name: quantity
        description: "Available stock quantity for the product in the store."

  - name: int_sales__orders
    description: "Intermediate model combining order items with orders, customers, staff, and store details."
    columns:
      - name: order_item_id
        description: "Unique identifier for oder and item"
        tests:
          - not_null
          - unique
      - name: store_product_id
        description: "Unique identifier for product in store"
        tests:
          - not_null
      - name: order_id
        description: "Unique identifier for each order."
        tests:
          - not_null
          - relationships:
              name: order_id_fk_to_orders
              arguments:
                to: ref('stg_sales__orders')
                field: order_id
      - name: order_date
        description: "Date when the order was placed."
      - name: required_date
        description: "Required delivery date for the order."
      - name: shipped_date
        description: "Date when the order was shipped."
      - name: order_status
        description: "Status of the order."
      - name: quantity
        description: "Quantity of the product in the order item."
      - name: list_price
        description: "List price per unit of the product."
      - name: discount
        description: "Discount applied to the product in the order."
      - name: total
        description: "Total amount for the order item after discount."
      - name: store_id
        description: "Identifier of the store where the order was placed."
        tests:
          - relationships:
              name: store_id_fk_to_stores
              arguments:
                to: ref('stg_sales__stores')
                field: store_id
      - name: store_name
        description: "Name of the store."
      - name: staff_id
        description: "Identifier of the staff member handling the order."
        tests:
          - relationships:
              name: staff_id_fk_to_staffs
              arguments:
                to: ref('stg_sales__staffs')
                field: staff_id
      - name: staff_name
        description: "Full name of the staff member."
      - name: customer_id
        description: "Identifier of the customer who placed the order."
        tests:
          - relationships:
              name: customer_id_fk_to_customers
              arguments:
                to: ref('stg_sales__customers')
                field: customer_id
      - name: customer_name
        description: "Full name of the customer."
      - name: customer_city
        description: "City of the customer."
      - name: customer_state
        description: "State of the customer."