version: 2

models:
  - name: int_sales_orders
    description: "Intermediate model joining orders with customers, stores, and staffs. Used to analyze order-level activity and responsible personnel."
    columns:
      - name: order_id
        description: "Primary key, unique identifier of the order."
        tests:
          - unique
          - not_null
      - name: order_date
        description: "Date the order was placed."
      - name: shipped_date
        description: "Date the order was shipped."
      - name: order_status
        description: "Current status of the order (e.g., shipped, delivered, canceled)."
        tests:
          - accepted_values:
              name: accepted_values_order_status
              values: ['created', 'approved', 'shipped', 'delivered', 'canceled', 'processing']
      - name: store_id
        description: "Foreign key linking to the store where the order was placed."
        tests:
          - relationships:
              to: ref('stg_sales__stores')
              field: store_id
      - name: staff_id
        description: "Foreign key linking to the staff responsible for the sale."
        tests:
          - relationships:
              to: ref('stg_sales__staffs')
              field: staff_id
      - name: customer_id
        description: "Foreign key linking to the customer who placed the order."
        tests:
          - relationships:
              to: ref('stg_sales__customers')
              field: customer_id
      - name: store_name
        description: "Name of the store where the order occurred."
      - name: staff_name
        description: "Full name of the staff handling the order."
      - name: customer_name
        description: "Full name of the customer who made the order."

  - name: int_sales_products
    description: "Intermediate model combining order items, product details, and related brand/category information. Serves as a base for sales and revenue analysis."
    columns:
      - name: order_id
        description: "Foreign key linking to the parent order."
        tests:
          - relationships:
              to: ref('int_sales_orders')
              field: order_id
      - name: product_id
        description: "Foreign key linking to the product sold."
        tests:
          - relationships:
              to: ref('stg_production__products')
              field: product_id
      - name: product_name
        description: "Name of the product."
      - name: brand_name
        description: "Brand of the product."
      - name: category_name
        description: "Category to which the product belongs."
      - name: quantity
        description: "Number of units sold for this product in this order."
      - name: list_price
        description: "List price per unit of the product."
      - name: discount
        description: "Discount applied to the product (0–1)."
        tests:
          - accepted_values:
              name: accepted_discount_range
              values: [0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30]
      - name: total
        description: "Total revenue generated by the order item after discount, computed as quantity * list_price * (1 - discount)."
      - name: order_date
        description: "Date when the order was placed."
      - name: store_id
        description: "Identifier of the store where the sale occurred."
      - name: staff_id
        description: "Identifier of the staff who managed the sale."
      - name: customer_id
        description: "Identifier of the customer who placed the order."

  - name: int_inventory_status
    description: "Intermediate model combining product, stock, and store information to analyze inventory levels and availability per location."
    columns:
      - name: store_id
        description: "Foreign key linking to the store."
        tests:
          - relationships:
              to: ref('stg_sales__stores')
              field: store_id
      - name: store_name
        description: "Name of the store."
      - name: product_id
        description: "Foreign key linking to the product."
        tests:
          - relationships:
              to: ref('stg_production__products')
              field: product_id
      - name: product_name
        description: "Name of the product."
      - name: category_name
        description: "Category of the product."
      - name: brand_name
        description: "Brand of the product."
      - name: stock_quantity
        description: "Quantity of this product currently available in the store."
        tests:
          - not_null
          - accepted_range:
              name: valid_stock_range
              min_value: 0