version: 2

models:
  - name: stg_production__products
    description: "Contains details about products available for sale."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
          - unique
          - not_null
      - name: category_id
        description: "Foreign key linking product to its category."
        tests:
          - relationships:
              arguments:
                to: ref('stg_production__categories')
                field: category_id
      - name: brand_id
        description: "Foreign key linking product to its brand."
        tests:
          - relationships:
              arguments:
                to: ref('stg_production__brands')
                field: brand_id
  - name: stg_production__categories
    description: "Contains product category information."
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category."
        tests:
          - unique
          - not_null

  - name: stg_production__brands
    description: "Contains brand information for products."
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
          - unique
          - not_null

  - name: stg_production__stocks
    description: "Contains quantity of each product available in each store."
    columns:
      - name: store_id
        description: "Foreign key linking stock to a store."
        tests:
          - relationships:
              arguments:
                to: ref('stg_sales__stores')
                field: store_id
      - name: product_id
        description: "Foreign key linking stock to a product."
        tests:
          - relationships:
              arguments:
                to: ref('stg_production__products')
                field: product_id
      - name: quantity
        description: "Number of units available in stock."