version: 2

sources:
  - name: sales
    schema: sales
    tables:
      - name: customers
      - name: order_items
      - name: orders
      - name: staffs
      - name: stores
  - name: production
    schema: production
    tables:
      - name: brands
      - name: categories
      - name: products
      - name: stocks